#!/usr/bin/env python3
"""Restore French accents in legacy blog posts that were generated with a
buggy system prompt instructing the model to omit accents. The mapping is
intentionally conservative: only words that have a single, unambiguous French
spelling and that don't collide with English technical vocabulary or with
proper nouns used in the codebase. Run after `git status` is clean.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

# Each entry: unaccented form -> accented form. Keys are matched
# case-insensitively at word boundaries; the original casing of the first
# character is preserved on the replacement.
REPLACEMENTS: dict[str, str] = {
    # 4+ letter words, unambiguous in a French SAP-consulting context
    "strategie": "stratégie",
    "strategies": "stratégies",
    "strategique": "stratégique",
    "strategiques": "stratégiques",
    "necessite": "nécessité",
    "necessites": "nécessités",
    "necessaire": "nécessaire",
    "necessaires": "nécessaires",
    "necessairement": "nécessairement",
    "decouvrez": "découvrez",
    "decouvrir": "découvrir",
    "decouverte": "découverte",
    "decouvertes": "découvertes",
    "decouvre": "découvre",
    "decouvrent": "découvrent",
    "realiste": "réaliste",
    "realistes": "réalistes",
    "realise": "réalisé",
    "realiser": "réaliser",
    "realisees": "réalisées",
    "realisation": "réalisation",
    "realisations": "réalisations",
    "eviter": "éviter",
    "evitez": "évitez",
    "evitent": "évitent",
    "eviterez": "éviterez",
    "evidemment": "évidemment",
    "pieges": "pièges",
    "piege": "piège",
    "formalise": "formalisé",
    "evolue": "évolué",
    "evoluer": "évoluer",
    "evolution": "évolution",
    "evolutions": "évolutions",
    "evolutif": "évolutif",
    "evolutifs": "évolutifs",
    "evolutive": "évolutive",
    "evolutives": "évolutives",
    "considerablement": "considérablement",
    "considerable": "considérable",
    "considerables": "considérables",
    "considere": "considéré",
    "consideres": "considérés",
    "considerer": "considérer",
    "consideree": "considérée",
    "considerees": "considérées",
    "presentation": "présentation",
    "presentations": "présentations",
    "presente": "présenté",
    "presenter": "présenter",
    "presentes": "présentés",
    "presentee": "présentée",
    "presentees": "présentées",
    "prerequis": "prérequis",
    "beneficier": "bénéficier",
    "beneficie": "bénéficie",
    "benefice": "bénéfice",
    "benefices": "bénéfices",
    "benefique": "bénéfique",
    "embarquee": "embarquée",
    "embarquees": "embarquées",
    "embarques": "embarqués",
    "deploie": "déploie",
    "deploient": "déploient",
    "deploiement": "déploiement",
    "deploiements": "déploiements",
    "deployer": "déployer",
    "deploye": "déployé",
    "deployes": "déployés",
    "deployee": "déployée",
    "deployees": "déployées",
    "desormais": "désormais",
    "apres": "après",
    "precisement": "précisément",
    "precise": "précise",
    "precises": "précises",
    "preciser": "préciser",
    "eclairer": "éclairer",
    "definition": "définition",
    "definitions": "définitions",
    "definit": "définit",
    "defini": "défini",
    "definie": "définie",
    "definis": "définis",
    "definies": "définies",
    "definir": "définir",
    "mecanisme": "mécanisme",
    "mecanismes": "mécanismes",
    "supporte": "supporté",
    "supportes": "supportés",
    "supportee": "supportée",
    "supportees": "supportées",
    "developpement": "développement",
    "developpements": "développements",
    "developper": "développer",
    "developpe": "développé",
    "developpes": "développés",
    "developpees": "développées",
    "developpee": "développée",
    "developpeur": "développeur",
    "developpeurs": "développeurs",
    "ameliore": "amélioré",
    "ameliorer": "améliorer",
    "ameliorees": "améliorées",
    "amelioree": "améliorée",
    "ameliores": "améliorés",
    "amelioration": "amélioration",
    "ameliorations": "améliorations",
    "simplifie": "simplifié",
    "simplifies": "simplifiés",
    "simplifiee": "simplifiée",
    "simplifiees": "simplifiées",
    "decision": "décision",
    "decisions": "décisions",
    "decisionnel": "décisionnel",
    "deciderez": "déciderez",
    "decider": "décider",
    "ecoute": "écoute",
    "ecouter": "écouter",
    "ecoutez": "écoutez",
    "experience": "expérience",
    "experiences": "expériences",
    "experimente": "expérimenté",
    "experimenter": "expérimenter",
    "europeen": "européen",
    "europeens": "européens",
    "europeenne": "européenne",
    "europeennes": "européennes",
    "francais": "français",
    "francaise": "française",
    "francaises": "françaises",
    "energie": "énergie",
    "energies": "énergies",
    "energetique": "énergétique",
    "energetiques": "énergétiques",
    "annees": "années",
    "annee": "année",
    "complementaire": "complémentaire",
    "complementaires": "complémentaires",
    "completer": "compléter",
    "completes": "complètes",
    "completement": "complètement",
    "elements": "éléments",
    "element": "élément",
    "etudie": "étudié",
    "etudier": "étudier",
    "etudiez": "étudiez",
    "etude": "étude",
    "etudes": "études",
    "evident": "évident",
    "evidente": "évidente",
    "evidents": "évidents",
    "evidentes": "évidentes",
    "etabli": "établi",
    "etablir": "établir",
    "etablie": "établie",
    "etablis": "établis",
    "etablies": "établies",
    "etablissement": "établissement",
    "ecrit": "écrit",
    "ecrite": "écrite",
    "ecrits": "écrits",
    "ecrites": "écrites",
    "echelle": "échelle",
    "echelles": "échelles",
    "echec": "échec",
    "echecs": "échecs",
    "ecart": "écart",
    "ecarts": "écarts",
    "egalement": "également",
    "specifique": "spécifique",
    "specifiques": "spécifiques",
    "specificite": "spécificité",
    "specificites": "spécificités",
    "systematique": "systématique",
    "systematiques": "systématiques",
    "systematiquement": "systématiquement",
    "systeme": "système",
    "systemes": "systèmes",
    "verifie": "vérifié",
    "verifies": "vérifiés",
    "verifier": "vérifier",
    "verifiez": "vérifiez",
    "verification": "vérification",
    "verifications": "vérifications",
    "modele": "modèle",
    "modeles": "modèles",
    "donnees": "données",
    "donnee": "donnée",
    "interet": "intérêt",
    "interets": "intérêts",
    "rapidite": "rapidité",
    "operationnel": "opérationnel",
    "operationnels": "opérationnels",
    "operationnelle": "opérationnelle",
    "operationnelles": "opérationnelles",
    "operation": "opération",
    "operations": "opérations",
    "generale": "générale",
    "generales": "générales",
    "generaux": "généraux",
    "generalement": "généralement",
    "generation": "génération",
    "generations": "générations",
    "generative": "générative",
    "generatif": "génératif",
    "qualite": "qualité",
    "qualites": "qualités",
    "deja": "déjà",
    "voila": "voilà",
    "interesse": "intéressé",
    "interessant": "intéressant",
    "interessante": "intéressante",
    "interessants": "intéressants",
    "interessantes": "intéressantes",
    "interesser": "intéresser",
    "interessez": "intéressez",
    "preparer": "préparer",
    "preparation": "préparation",
    "preparations": "préparations",
    "prepare": "préparé",
    "prepares": "préparés",
    "preparee": "préparée",
    "preparees": "préparées",
    "responsabilite": "responsabilité",
    "responsabilites": "responsabilités",
    "competences": "compétences",
    "competence": "compétence",
    "competent": "compétent",
    "competents": "compétents",
    "competente": "compétente",
    "competentes": "compétentes",
    "scenario": "scénario",
    "scenarios": "scénarios",
    "regle": "règle",
    "regles": "règles",
    "regler": "régler",
    "redaction": "rédaction",
    "redige": "rédigé",
    "rediger": "rédiger",
    "rediges": "rédigés",
    "redigez": "rédigez",
    "succes": "succès",
    "ecosysteme": "écosystème",
    "ecosystemes": "écosystèmes",
    "implementation": "implémentation",
    "implementations": "implémentations",
    "implementer": "implémenter",
    "implemente": "implémenté",
    "implementes": "implémentés",
    "implementee": "implémentée",
    "implementees": "implémentées",
    "controle": "contrôle",
    "controles": "contrôles",
    "controler": "contrôler",
    "evaluer": "évaluer",
    "evaluation": "évaluation",
    "evaluations": "évaluations",
    "evalue": "évalué",
    "evalues": "évalués",
    "evaluee": "évaluée",
    "evaluees": "évaluées",
    "regulier": "régulier",
    "reguliere": "régulière",
    "regulierement": "régulièrement",
    "reguliers": "réguliers",
    "regulieres": "régulières",
    "verite": "vérité",
    "verites": "vérités",
    "etape": "étape",
    "etapes": "étapes",
    "delicat": "délicat",
    "delicate": "délicate",
    "delicats": "délicats",
    "delicates": "délicates",
    "delegue": "délégué",
    "delegues": "délégués",
    "deleguer": "déléguer",
    "delegation": "délégation",
    "delegations": "délégations",
    "delivre": "délivré",
    "delivrer": "délivrer",
    "delivres": "délivrés",
    "delivree": "délivrée",
    "delivrees": "délivrées",
    "delais": "délais",
    "delai": "délai",
    "elabore": "élaboré",
    "elaborer": "élaborer",
    "elaboree": "élaborée",
    "elaborees": "élaborées",
    "elabores": "élaborés",
    "elaboration": "élaboration",
    "selection": "sélection",
    "selections": "sélections",
    "selectionne": "sélectionné",
    "selectionner": "sélectionner",
    "selectionnes": "sélectionnés",
    "selectionnee": "sélectionnée",
    "selectionnees": "sélectionnées",
    "perimetre": "périmètre",
    "perimetres": "périmètres",
    "premiere": "première",
    "premieres": "premières",
    "derniere": "dernière",
    "dernieres": "dernières",
    "probleme": "problème",
    "problemes": "problèmes",
    "theme": "thème",
    "themes": "thèmes",
    "schema": "schéma",
    "schemas": "schémas",
    "demarche": "démarche",
    "demarches": "démarches",
    "demarrer": "démarrer",
    "demarrage": "démarrage",
    "demarrages": "démarrages",
    "demarre": "démarré",
    "demarres": "démarrés",
    "demarrent": "démarrent",
    "deconseille": "déconseillé",
    "deroulement": "déroulement",
    "derouler": "dérouler",
    "deroule": "déroulé",
    "metier": "métier",
    "metiers": "métiers",
    "fideliser": "fidéliser",
    "fidelite": "fidélité",
    "fideles": "fidèles",
    "fidele": "fidèle",
    "modeliser": "modéliser",
    "modelisation": "modélisation",
    "modelisations": "modélisations",
    "modelise": "modélisé",
    "modelises": "modélisés",
    "deteriore": "détérioré",
    "deteriorer": "détériorer",
    "renforce": "renforcé",
    "renforces": "renforcés",
    "renforcee": "renforcée",
    "renforcees": "renforcées",
    "decoupage": "découpage",
    "decouper": "découper",
    "decoupe": "découpé",
    "decoupes": "découpés",
    "rectifie": "rectifié",
    "renouvelee": "renouvelée",
    "renouvelees": "renouvelées",
    "ecran": "écran",
    "ecrans": "écrans",
    "exteriorite": "extériorité",
    "interieur": "intérieur",
    "interieurs": "intérieurs",
    "interieure": "intérieure",
    "interieures": "intérieures",
    "exterieur": "extérieur",
    "exterieurs": "extérieurs",
    "exterieure": "extérieure",
    "exterieures": "extérieures",
    "perpetuel": "perpétuel",
    "perpetuelle": "perpétuelle",
    "perpetuels": "perpétuels",
    "perpetuelles": "perpétuelles",
    "fenetre": "fenêtre",
    "fenetres": "fenêtres",
    "transferes": "transférés",
    "transfere": "transféré",
    "transferer": "transférer",
    "controlee": "contrôlée",
    "controlees": "contrôlées",
    "controles": "contrôlés",
    "demontrer": "démontrer",
    "demontre": "démontré",
    "demonstration": "démonstration",
    "demonstrations": "démonstrations",
    "echeance": "échéance",
    "echeances": "échéances",
    "echelonne": "échelonné",
    "echelonnee": "échelonnée",
    "echelonnees": "échelonnées",
    "echelonner": "échelonner",
    "consequent": "conséquent",
    "consequents": "conséquents",
    "consequente": "conséquente",
    "consequentes": "conséquentes",
    "consequence": "conséquence",
    "consequences": "conséquences",
    "experimentation": "expérimentation",
    "experimentations": "expérimentations",
    "experimente": "expérimenté",
    "experimentes": "expérimentés",
    "experimentee": "expérimentée",
    "experimentees": "expérimentées",
    "regenerer": "régénérer",
    "regeneres": "régénérés",
    "incoherent": "incohérent",
    "incoherente": "incohérente",
    "incoherents": "incohérents",
    "incoherentes": "incohérentes",
    "coherent": "cohérent",
    "coherente": "cohérente",
    "coherents": "cohérents",
    "coherentes": "cohérentes",
    "coherence": "cohérence",
    "renover": "rénover",
    "renove": "rénové",
    "renovee": "rénovée",
    "renoves": "rénovés",
    "renovees": "rénovées",
    "renovation": "rénovation",
    "renovations": "rénovations",
    "tres": "très",
    "agrement": "agrément",
    "agrements": "agréments",
    "deroule": "déroulé",
    "deroules": "déroulés",
    "derouler": "dérouler",
    "interpretation": "interprétation",
    "interpretations": "interprétations",
    "interpreter": "interpréter",
    "interprete": "interprété",
    "interpretes": "interprétés",
    "demarche": "démarche",
    "ere": "ère",
    "etre": "être",
    "etres": "êtres",
    "meme": "même",
    "memes": "mêmes",
    "deja": "déjà",
    "geree": "gérée",
    "geres": "gérés",
    "gerer": "gérer",
    "gere": "géré",
    "gerees": "gérées",
    "fiabilite": "fiabilité",
    "fiabilites": "fiabilités",
    "rigidite": "rigidité",
    "stabilite": "stabilité",
    "fragilite": "fragilité",
    "lisibilite": "lisibilité",
    "visibilite": "visibilité",
    "compatibilite": "compatibilité",
    "compatibilites": "compatibilités",
    "interoperabilite": "interopérabilité",
    "perennite": "pérennité",
    "perenne": "pérenne",
    "perennes": "pérennes",
    "perenniser": "pérenniser",
    "valide": "validé",
    "valides": "validés",
    "validee": "validée",
    "validees": "validées",
    "anciennete": "ancienneté",
    "anciennetes": "anciennetés",
    "deplacer": "déplacer",
    "deplace": "déplacé",
    "deplaces": "déplacés",
    "deplacement": "déplacement",
    "deplacements": "déplacements",
    "decortiquer": "décortiquer",
    "decortique": "décortiqué",
    "decortiques": "décortiqués",
    "concernee": "concernée",
    "concernees": "concernées",
    "concerne": "concerné",
    "concernes": "concernés",
    "decret": "décret",
    "decrets": "décrets",
    "redresses": "redressés",
    "redresse": "redressé",
    "etranger": "étranger",
    "etrangers": "étrangers",
    "etrangere": "étrangère",
    "etrangeres": "étrangères",
    "decideurs": "décideurs",
    "decideur": "décideur",
    "decideuse": "décideuse",
    "decideuses": "décideuses",
    "redaction": "rédaction",
    "redacteur": "rédacteur",
    "redacteurs": "rédacteurs",
    "veritable": "véritable",
    "veritables": "véritables",
    "veritablement": "véritablement",
    "imperative": "impérative",
    "imperatives": "impératives",
    "imperatif": "impératif",
    "imperatifs": "impératifs",
    "imperativement": "impérativement",
    "litterature": "littérature",
    "intermediaire": "intermédiaire",
    "intermediaires": "intermédiaires",
    "incomplete": "incomplète",
    "incompletes": "incomplètes",
    "interferer": "interférer",
    "interfere": "interféré",
    "interferes": "interférés",
    "ame": "âme",
    "ames": "âmes",
    "fache": "fâché",
    "faches": "fâchés",
    "tache": "tâche",
    "taches": "tâches",
    "tachee": "tâchée",
    "tachees": "tâchées",
    "ages": "âges",
    "age": "âge",
    "controler": "contrôler",
    "controlons": "contrôlons",
    "controlent": "contrôlent",
    "controlerai": "contrôlerai",
    "controles": "contrôles",
    "couteux": "coûteux",
    "couteuse": "coûteuse",
    "couteuses": "coûteuses",
    "couts": "coûts",
    "cout": "coût",
    "couter": "coûter",
    "coute": "coûte",
    "coutent": "coûtent",
    "couta": "coûta",
    "interet": "intérêt",
    "interets": "intérêts",
    "interrogees": "interrogées",
    "interrogee": "interrogée",
    "interroge": "interrogé",
    "interroges": "interrogés",
    "decroche": "décroché",
    "decroches": "décrochés",
    "decrocher": "décrocher",
    "exhorte": "exhorté",
    "exhortes": "exhortés",
    "deuxieme": "deuxième",
    "deuxiemes": "deuxièmes",
    "troisieme": "troisième",
    "troisiemes": "troisièmes",
    "quatrieme": "quatrième",
    "quatriemes": "quatrièmes",
    "cinquieme": "cinquième",
    "cinquiemes": "cinquièmes",
    "sixieme": "sixième",
    "sixiemes": "sixièmes",
    "septieme": "septième",
    "huitieme": "huitième",
    "neuvieme": "neuvième",
    "dixieme": "dixième",
    "demarrer": "démarrer",
    "Etat": "État",
    "Etats": "États",
    "etat": "état",
    "etats": "états",
    # Second-pass additions detected in legacy posts
    "securite": "sécurité",
    "securites": "sécurités",
    "cle": "clé",
    "cles": "clés",
    "complexite": "complexité",
    "complexites": "complexités",
    "references": "références",
    "reference": "référence",
    "capacite": "capacité",
    "capacites": "capacités",
    "activite": "activité",
    "activites": "activités",
    "particulierement": "particulièrement",
    "maniere": "manière",
    "manieres": "manières",
    "concretement": "concrètement",
    "realite": "réalité",
    "realites": "réalités",
    "automatise": "automatisé",
    "automatises": "automatisés",
    "automatisee": "automatisée",
    "automatisees": "automatisées",
    "differente": "différente",
    "differentes": "différentes",
    "different": "différent",
    "differents": "différents",
    "difference": "différence",
    "differences": "différences",
    "simplicite": "simplicité",
    "simplicites": "simplicités",
    "opportunite": "opportunité",
    "opportunites": "opportunités",
    "nouveaute": "nouveauté",
    "nouveautes": "nouveautés",
    "maturite": "maturité",
    "maturites": "maturités",
    "frequemment": "fréquemment",
    "chere": "chère",
    "cheres": "chères",
    "theorique": "théorique",
    "theoriques": "théoriques",
    "theorie": "théorie",
    "theories": "théories",
    "recemment": "récemment",
    "nuancee": "nuancée",
    "nuancees": "nuancées",
    "societe": "société",
    "societes": "sociétés",
    "communaute": "communauté",
    "communautes": "communautés",
    "humanite": "humanité",
    "mobilite": "mobilité",
    "agilite": "agilité",
    "accessibilite": "accessibilité",
    "criticite": "criticité",
    "finalite": "finalité",
    "finalites": "finalités",
    "entierement": "entièrement",
    "legerement": "légèrement",
    "entiere": "entière",
    "entieres": "entières",
    "preferer": "préférer",
    "prefere": "préféré",
    "preferes": "préférés",
    "preferee": "préférée",
    "preferees": "préférées",
    "caractere": "caractère",
    "caracteres": "caractères",
    "caracterise": "caractérisé",
    "caracterises": "caractérisés",
    "caracterisee": "caractérisée",
    "caracterisees": "caractérisées",
    "caracteriser": "caractériser",
    "enquete": "enquête",
    "enquetes": "enquêtes",
    "procedure": "procédure",
    "procedures": "procédures",
    "methode": "méthode",
    "methodes": "méthodes",
    "methodologie": "méthodologie",
    "methodologies": "méthodologies",
    "methodologique": "méthodologique",
    "methodologiques": "méthodologiques",
    "frequence": "fréquence",
    "frequences": "fréquences",
    "recurrence": "récurrence",
    "recurrences": "récurrences",
    "specificite": "spécificité",
    "tete": "tête",
    "tetes": "têtes",
    "fete": "fête",
    "fetes": "fêtes",
    "fenetre": "fenêtre",
    "fenetres": "fenêtres",
    "tres": "très",
    "pres": "près",
    "apres": "après",
    "meme": "même",
    "memes": "mêmes",
    "etre": "être",
    "etres": "êtres",
    "deja": "déjà",
    "voila": "voilà",
    "celebre": "célèbre",
    "celebres": "célèbres",
    "celebrer": "célébrer",
    "siecle": "siècle",
    "siecles": "siècles",
    "ere": "ère",
    "viabilite": "viabilité",
    "faisabilite": "faisabilité",
    "fiabilites": "fiabilités",
    "fragilites": "fragilités",
    "criticites": "criticités",
    "vitalite": "vitalité",
    "modalite": "modalité",
    "modalites": "modalités",
    "modalitee": "modalité",
    "modalitees": "modalités",
    "formalite": "formalité",
    "formalites": "formalités",
    "sensibilite": "sensibilité",
    "sensibilites": "sensibilités",
    "diversite": "diversité",
    "totalite": "totalité",
    "identite": "identité",
    "identites": "identités",
    "rapidite": "rapidité",
    "rapidites": "rapidités",
    "competitivite": "compétitivité",
    "exhaustivite": "exhaustivité",
    "lege": "lège",
    "evenement": "événement",
    "evenements": "événements",
    "Evenement": "Événement",
    "Evenements": "Événements",
    "premiere": "première",
    "premieres": "premières",
    "derniere": "dernière",
    "dernieres": "dernières",
    "particuliere": "particulière",
    "particulieres": "particulières",
    "deuxieme": "deuxième",
    "deuxiemes": "deuxièmes",
    "troisieme": "troisième",
    "troisiemes": "troisièmes",
    "quatrieme": "quatrième",
    "quatriemes": "quatrièmes",
    "cinquieme": "cinquième",
    "cinquiemes": "cinquièmes",
    "sixieme": "sixième",
    "septieme": "septième",
    "huitieme": "huitième",
    "neuvieme": "neuvième",
    "dixieme": "dixième",
    # Third pass — more frequent missing accents
    "arriere": "arrière",
    "arrieres": "arrières",
    "autorite": "autorité",
    "autorites": "autorités",
    "beneficierez": "bénéficierez",
    "comite": "comité",
    "comites": "comités",
    "comptabilite": "comptabilité",
    "comptabilites": "comptabilités",
    "confidentialite": "confidentialité",
    "conformite": "conformité",
    "conformites": "conformités",
    "continuite": "continuité",
    "critere": "critère",
    "criteres": "critères",
    "cybersecurite": "cybersécurité",
    "depassements": "dépassements",
    "depassement": "dépassement",
    "creer": "créer",
    "cree": "créé",
    "crees": "créés",
    "creee": "créée",
    "creees": "créées",
    "creation": "création",
    "creations": "créations",
    "createur": "créateur",
    "createurs": "créateurs",
    "createrice": "créatrice",
    "creatives": "créatives",
    "creative": "créative",
    "creatif": "créatif",
    "creatifs": "créatifs",
    "ideal": "idéal",
    "ideale": "idéale",
    "ideaux": "idéaux",
    "ideales": "idéales",
    "idealement": "idéalement",
    "idee": "idée",
    "idees": "idées",
    "agree": "agréé",
    "agrees": "agréés",
    "fermee": "fermée",
    "fermees": "fermées",
    "fermes": "fermés",
    "delivrable": "livrable",
    "previsible": "prévisible",
    "previsibles": "prévisibles",
    "imprevu": "imprévu",
    "imprevus": "imprévus",
    "imprevue": "imprévue",
    "imprevues": "imprévues",
    "prevue": "prévue",
    "prevues": "prévues",
    "prevus": "prévus",
    "prevu": "prévu",
    "prevoit": "prévoit",
    "prevoir": "prévoir",
    "prevu": "prévu",
    "echeancier": "échéancier",
    "echeanciers": "échéanciers",
    "alea": "aléa",
    "aleas": "aléas",
    "aleatoire": "aléatoire",
    "aleatoires": "aléatoires",
    "interconnecte": "interconnecté",
    "interconnectee": "interconnectée",
    "interconnectes": "interconnectés",
    "interconnectees": "interconnectées",
    "homogene": "homogène",
    "homogenes": "homogènes",
    "heterogene": "hétérogène",
    "heterogenes": "hétérogènes",
    "evidence": "évidence",
    "evidences": "évidences",
    "remedier": "remédier",
    "remede": "remède",
    "remedes": "remèdes",
    "secrete": "secrète",
    "concrete": "concrète",
    "concretes": "concrètes",
    "discrete": "discrète",
    "discretement": "discrètement",
    "celibataire": "célibataire",
    "modere": "modéré",
    "moderee": "modérée",
    "moderees": "modérées",
    "moderes": "modérés",
    "modereement": "modérément",
    "tolerance": "tolérance",
    "tolerances": "tolérances",
    "tolere": "toléré",
    "toleres": "tolérés",
    "toleree": "tolérée",
    "tolerees": "tolérées",
    "tolerer": "tolérer",
    "decrete": "décrété",
    "decreter": "décréter",
    "negocier": "négocier",
    "negocie": "négocié",
    "negocies": "négociés",
    "negociee": "négociée",
    "negociees": "négociées",
    "negociation": "négociation",
    "negociations": "négociations",
    "predit": "prédit",
    "predire": "prédire",
    "Predit": "Prédit",
    "predits": "prédits",
    "prediction": "prédiction",
    "predictions": "prédictions",
    "predictive": "prédictive",
    "predictif": "prédictif",
    "predictives": "prédictives",
    "predictifs": "prédictifs",
    "redaction": "rédaction",
    "redactions": "rédactions",
    "remunerer": "rémunérer",
    "remunere": "rémunéré",
    "remuneres": "rémunérés",
    "remuneration": "rémunération",
    "remunerations": "rémunérations",
    "elementaire": "élémentaire",
    "elementaires": "élémentaires",
    "agree": "agréé",
    "agreee": "agréée",
    "agrees": "agréés",
    "agreees": "agréées",
    "preserve": "préservé",
    "preserves": "préservés",
    "preserver": "préserver",
    "preservation": "préservation",
    "incoherence": "incohérence",
    "incoherences": "incohérences",
    "amorce": "amorcé",
    "amorces": "amorcés",
    "tempere": "tempéré",
    "temperees": "tempérées",
    "tempete": "tempête",
    "tempetes": "tempêtes",
    "interopere": "interopère",
    "intereoperabilite": "interopérabilité",
    "Etudie": "Étudié",
    "Specifique": "Spécifique",
    "epuise": "épuisé",
    "epuises": "épuisés",
    "epuisement": "épuisement",
    "deroutant": "déroutant",
    "decourageant": "décourageant",
    "Frequence": "Fréquence",
    "Probleme": "Problème",
    "Apres": "Après",
    "Premiere": "Première",
    "Derniere": "Dernière",
    "Etape": "Étape",
    "Etapes": "Étapes",
    "frequence": "fréquence",
    "Frequences": "Fréquences",
    "Methode": "Méthode",
    "Methodes": "Méthodes",
    "Methodologie": "Méthodologie",
    "Methodologies": "Méthodologies",
    "Procedure": "Procédure",
    "Procedures": "Procédures",
    "Strategie": "Stratégie",
    "Strategies": "Stratégies",
    "Securite": "Sécurité",
    "Cybersecurite": "Cybersécurité",
    "Communaute": "Communauté",
    "obsolete": "obsolète",
    "obsoletes": "obsolètes",
    "migrees": "migrées",
    "migree": "migrée",
    "migres": "migrés",
    "migre": "migré",
    "equivalent": "équivalent",
    "equivalents": "équivalents",
    "equivalente": "équivalente",
    "equivalentes": "équivalentes",
    "equivalence": "équivalence",
    "nettoyees": "nettoyées",
    "nettoyee": "nettoyée",
    "nettoye": "nettoyé",
    "nettoyes": "nettoyés",
    "recommande": "recommandé",
    "recommandes": "recommandés",
    "recommandee": "recommandée",
    "recommandees": "recommandées",
    "maitre": "maître",
    "maitres": "maîtres",
    "maitresse": "maîtresse",
    "maitresses": "maîtresses",
    "maitrise": "maîtrise",
    "maitrises": "maîtrises",
    "maitriser": "maîtriser",
    "maitrisee": "maîtrisée",
    "maitrisees": "maîtrisées",
    "maitrises": "maîtrisés",
    "maitrise": "maîtrise",
    "deroutant": "déroutant",
    "rates": "ratés",
    "rate": "raté",
    "ratee": "ratée",
    "ratees": "ratées",
    "interfere": "interfère",
    "interferent": "interfèrent",
    "litterature": "littérature",
    "litteratures": "littératures",
    "rentabilite": "rentabilité",
    "rentabilites": "rentabilités",
    "stabilite": "stabilité",
    "stabilites": "stabilités",
    "fragilite": "fragilité",
    "lisibilite": "lisibilité",
    "lisibilites": "lisibilités",
    "visibilite": "visibilité",
    "compatibilite": "compatibilité",
    "compatibilites": "compatibilités",
    "interoperabilite": "interopérabilité",
    "perennite": "pérennité",
    "perenne": "pérenne",
    "perennes": "pérennes",
    "perenniser": "pérenniser",
    "anciennete": "ancienneté",
    "anciennetes": "anciennetés",
    "deplacer": "déplacer",
    "deplace": "déplacé",
    "deplaces": "déplacés",
    "deplacement": "déplacement",
    "deplacements": "déplacements",
    "decortiquer": "décortiquer",
    "decortique": "décortiqué",
    "decortiques": "décortiqués",
    "concernee": "concernée",
    "concernees": "concernées",
    "concerne": "concerné",
    "concernes": "concernés",
    "etranger": "étranger",
    "etrangers": "étrangers",
    "etrangere": "étrangère",
    "etrangeres": "étrangères",
    "decideurs": "décideurs",
    "decideur": "décideur",
    "decideuse": "décideuse",
    "decideuses": "décideuses",
    "redacteur": "rédacteur",
    "redacteurs": "rédacteurs",
    "veritable": "véritable",
    "veritables": "véritables",
    "veritablement": "véritablement",
    "imperative": "impérative",
    "imperatives": "impératives",
    "imperatif": "impératif",
    "imperatifs": "impératifs",
    "imperativement": "impérativement",
    "intermediaire": "intermédiaire",
    "intermediaires": "intermédiaires",
    "interferer": "interférer",
    "complement": "complément",
    "complements": "compléments",
    "supplement": "supplément",
    "supplements": "suppléments",
    "supplementaire": "supplémentaire",
    "supplementaires": "supplémentaires",
    "experimental": "expérimental",
    "experimentale": "expérimentale",
    "experimentaux": "expérimentaux",
    "experimentales": "expérimentales",
    "Methode": "Méthode",
    "preference": "préférence",
    "preferences": "préférences",
    "preferable": "préférable",
    "preferables": "préférables",
    "achevement": "achèvement",
    "acheve": "achevé",
    "acheves": "achevés",
    "achevee": "achevée",
    "achevees": "achevées",
    "deviation": "déviation",
    "deviations": "déviations",
    "devie": "dévié",
    "devies": "déviés",
    "devier": "dévier",
    "deroge": "dérogé",
    "deroger": "déroger",
    "derogation": "dérogation",
    "derogations": "dérogations",
    "presence": "présence",
    "presences": "présences",
    "evaluable": "évaluable",
    "evaluables": "évaluables",
    "envisage": "envisagé",
    "envisages": "envisagés",
    "envisagee": "envisagée",
    "envisagees": "envisagées",
    "modeliser": "modéliser",
    "modelisation": "modélisation",
    "modelisations": "modélisations",
    "modelise": "modélisé",
    "modelises": "modélisés",
    "remontees": "remontées",
    "remontee": "remontée",
    "decoulant": "découlant",
    "decoule": "découle",
    "decoulent": "découlent",
    "regissent": "régissent",
    "regir": "régir",
    "regi": "régi",
    "regis": "régis",
    "regie": "régie",
    "regies": "régies",
    "complete": "complète",
    "completes": "complètes",
    "Societe": "Société",
}


def replace_word(match: re.Match[str]) -> str:
    word = match.group(0)
    repl = REPLACEMENTS[word.lower()]
    if word[0].isupper():
        return repl[0].upper() + repl[1:]
    return repl


def build_regex() -> re.Pattern[str]:
    keys = sorted(REPLACEMENTS.keys(), key=len, reverse=True)
    pattern = r"(?<![A-Za-zÀ-ÿ])(" + "|".join(re.escape(k) for k in keys) + r")(?![A-Za-zÀ-ÿ])"
    return re.compile(pattern, re.IGNORECASE)


def fix_text(text: str, rx: re.Pattern[str]) -> tuple[str, int]:
    new_text, count = rx.subn(replace_word, text)
    return new_text, count


# Unambiguous multi-word phrases where the bare letter "a" is necessarily the
# preposition "à" (never the verb "avoir"). Limited to patterns where the
# surrounding tokens make the sense unambiguous.
PHRASE_FIXES: list[tuple[str, str]] = [
    (r"\bmises\s+a\s+jour\b", "mises à jour"),
    (r"\bmise\s+a\s+jour\b", "mise à jour"),
    (r"\bmises\s+a\s+niveau\b", "mises à niveau"),
    (r"\bmise\s+a\s+niveau\b", "mise à niveau"),
    (r"\bgrace\s+a\b", "grâce à"),
    (r"\bGrace\s+a\b", "Grâce à"),
    (r"\bface\s+a\b", "face à"),
    (r"\bquant\s+a\b", "quant à"),
    (r"\ba\s+partir\s+de\b", "à partir de"),
    (r"\bA\s+partir\s+de\b", "À partir de"),
    (r"\ba\s+propos\b", "à propos"),
    (r"\ba\s+peine\b", "à peine"),
    (r"\ba\s+jamais\b", "à jamais"),
    (r"\ba\s+chaque\b", "à chaque"),
    (r"\bA\s+chaque\b", "À chaque"),
    (r"\ba\s+venir\b", "à venir"),
    (r"\bA\s+venir\b", "À venir"),
    (r"\ba\s+travers\b", "à travers"),
    (r"\bA\s+travers\b", "À travers"),
    (r"\ba\s+nouveau\b", "à nouveau"),
    (r"\bA\s+nouveau\b", "À nouveau"),
    (r"\ba\s+l'oppose\b", "à l'opposé"),
    (r"\ba\s+l'inverse\b", "à l'inverse"),
    (r"\bA\s+l'inverse\b", "À l'inverse"),
    (r"\ba\s+l'origine\b", "à l'origine"),
    (r"\bA\s+l'origine\b", "À l'origine"),
    (r"\ba\s+l'echelle\b", "à l'échelle"),
    (r"\bjusqu'a\b", "jusqu'à"),
    (r"\bJusqu'a\b", "Jusqu'à"),
    (r"\b(?<!')(?<![\w])lorsqu'a\b", "lorsqu'à"),
    (r"\bvis-a-vis\b", "vis-à-vis"),
    (r"\b(?:c|C)elui-la\b", lambda m: ("Celui-là" if m.group(0)[0] == "C" else "celui-là")),
    (r"\b(?:c|C)elle-la\b", lambda m: ("Celle-là" if m.group(0)[0] == "C" else "celle-là")),
    (r"\bceux-la\b", "ceux-là"),
    (r"\bcelles-la\b", "celles-là"),
    (r"\bla-bas\b", "là-bas"),
    (r"\bla-dessus\b", "là-dessus"),
    (r"\bla-dessous\b", "là-dessous"),
    (r"\bdes\s+lors\b", "dès lors"),
    (r"\bDes\s+lors\b", "Dès lors"),
    (r"\bdes\s+que\b", "dès que"),
    (r"\bDes\s+que\b", "Dès que"),
    # "ou" -> "où" only when followed by determiners that make it a relative
    # adverb of place rather than the conjunction "ou" (or).
    (r"\bou\s+les\s+extensions\b", "où les extensions"),
    (r"\bla\s+ou\b", "là où"),
    (r"\bd'ou\b", "d'où"),
    (r"\bD'ou\b", "D'où"),
    (r"\ba\s+la\s+mode\b", "à la mode"),
    (r"\b([Dd]e\s+\w+)\s+a\s+([A-Z])", r"\1 à \2"),
    (r"\bdesormais\s+a\b", "désormais à"),
    (r"\bdéjà\s+a\b", "déjà à"),
    (r"\bdéploie\s+(\w+\s+)?a\s+un\b", lambda m: m.group(0).replace(" a ", " à ")),
    (r"\bmaniere\s+a\s+", "manière à "),
    (r"\bmanière\s+a\s+", "manière à "),
    (r"\bsysteme\s+ou\s+chaque\b", "système où chaque"),
    (r"\bsystème\s+ou\s+chaque\b", "système où chaque"),
    (r"\b(\w+)\s+ou\s+chaque\b", r"\1 où chaque"),
    (r"\b(c'est\s+un\s+système)\s+ou\b", r"\1 où"),
    (r"\b(C'est\s+un\s+système)\s+ou\b", r"\1 où"),
    (r"\bjusqu\s+a\b", "jusqu'à"),
    (r"\bquasiment\s+a\b", "quasiment à"),
    (r"\bsuffit\s+a\b", "suffit à"),
    (r"\baboutit\s+a\b", "aboutit à"),
    (r"\bconduit\s+a\b", "conduit à"),
    (r"\bcontribue\s+a\b", "contribue à"),
    (r"\baide\s+a\b", "aide à"),
    (r"\baident\s+a\b", "aident à"),
    (r"\bservent\s+a\b", "servent à"),
    (r"\bsert\s+a\b", "sert à"),
    (r"\bvise\s+a\b", "vise à"),
    (r"\bvisent\s+a\b", "visent à"),
    (r"\bcommence\s+a\b", "commence à"),
    (r"\bcommencent\s+a\b", "commencent à"),
    (r"\bcontinue\s+a\b", "continue à"),
    (r"\bcontinuent\s+a\b", "continuent à"),
    (r"\bparvient\s+a\b", "parvient à"),
    (r"\bparviennent\s+a\b", "parviennent à"),
    (r"\bcherche\s+a\b", "cherche à"),
    (r"\bcherchent\s+a\b", "cherchent à"),
    (r"\bhesite\s+a\b", "hésite à"),
    (r"\bhesitent\s+a\b", "hésitent à"),
    (r"\bdestines?\s+a\b", lambda m: m.group(0).replace(" a", " à")),
    (r"\bdestinees?\s+a\b", lambda m: m.group(0).replace(" a", " à")),
    (r"\b(\d+)\s+a\s+(\d+)\b", r"\1 à \2"),
    (r"\b(de\s+\w+)\s+a\s+(\w+)\b", r"\1 à \2"),
]


def fix_blog_post(path: Path, rx: re.Pattern[str]) -> int:
    raw = path.read_text(encoding="utf-8")
    data = json.loads(raw)
    total = 0

    def transform(text: str) -> tuple[str, int]:
        new_text, count = fix_text(text, rx)
        for pattern, repl in PHRASE_FIXES:
            new_text, n = re.subn(pattern, repl, new_text)
            count += n
        return new_text, count

    for key in ("title", "excerpt", "content"):
        if key in data and isinstance(data[key], str):
            data[key], n = transform(data[key])
            total += n
    if "tags" in data and isinstance(data["tags"], list):
        for i, tag in enumerate(data["tags"]):
            if isinstance(tag, str):
                data["tags"][i], n = transform(tag)
                total += n
    if total > 0:
        path.write_text(
            json.dumps(data, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    return total


def main() -> int:
    blog_dir = Path(__file__).resolve().parent.parent / "content" / "blog"
    if not blog_dir.is_dir():
        print(f"Blog dir not found: {blog_dir}", file=sys.stderr)
        return 1
    rx = build_regex()
    grand_total = 0
    for path in sorted(blog_dir.glob("*.json")):
        n = fix_blog_post(path, rx)
        grand_total += n
        print(f"  {path.name}: {n} accents restored")
    print(f"\nTotal: {grand_total} accents restored across {len(list(blog_dir.glob('*.json')))} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
